config/routes.rb
Facekick::Application.routes.draw do
  resources :volunteers

  resources :non_profits

  get "public/index"
  
  match "" => "public#index"

end

app/models/non_profit.rb
class NonProfit < ActiveRecord::Base
  
  def get_image
    return image || 'default.jpg'
  end
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  
  def get_image
    return image || 'default.jpg'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/non_profits_controller.rb
class NonProfitsController < ApplicationController
  # GET /non_profits
  # GET /non_profits.xml
  def index
    @non_profits = NonProfit.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @non_profits }
    end
  end

  # GET /non_profits/1
  # GET /non_profits/1.xml
  def show
    @non_profit = NonProfit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @non_profit }
    end
  end

  # GET /non_profits/new
  # GET /non_profits/new.xml
  def new
    @non_profit = NonProfit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @non_profit }
    end
  end

  # GET /non_profits/1/edit
  def edit
    @non_profit = NonProfit.find(params[:id])
    @non_profit.password = ''
  end

  # POST /non_profits
  # POST /non_profits.xml
  def create
    handle_image_upload(params)
    
    to_create = params[:non_profit].clone
    to_create['password'] = (Digest::SHA2.new << to_create['password']).to_s
    
    @non_profit = NonProfit.new(params[:non_profit])

    respond_to do |format|
      if @non_profit.save
        format.html { redirect_to(@non_profit, :notice => 'Non profit was successfully created.') }
        format.xml  { render :xml => @non_profit, :status => :created, :location => @non_profit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @non_profit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /non_profits/1
  # PUT /non_profits/1.xml
  def update
    handle_image_upload(params)
    
    @non_profit = NonProfit.find(params[:id])

    respond_to do |format|
      to_update = params[:non_profit].clone
    if to_update['password'] != ''
      to_update['password'] = (Digest::SHA2.new << to_update['password']).to_s
    else
      to_update.delete('password') # remove password from update params
    end
      
      if @non_profit.update_attributes(params[:non_profit])
        format.html { redirect_to(@non_profit, :notice => 'Non profit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @non_profit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /non_profits/1
  # DELETE /non_profits/1.xml
  def destroy
    @non_profit = NonProfit.find(params[:id])
    @non_profit.destroy

    respond_to do |format|
      format.html { redirect_to(non_profits_url) }
      format.xml  { head :ok }
    end
  end
  
  private

  def handle_image_upload(params)
    if params[:image]
      uploaded_io = params[:image]
      File.open(Rails.root.join('public', 'images','non_profits',
          uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
      end
      params[:non_profit]['image'] = uploaded_io.original_filename
    end
  end
  
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  
  before_filter :load_volunteers
  
  def index
    @volunteers = Volunteer.all
  end
  
  def load_volunteers
    @volunteers = Volunteer.all
  end

end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  # GET /volunteers
  # GET /volunteers.xml
  def index
    @volunteers = Volunteer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @volunteers }
    end
  end

  # GET /volunteers/1
  # GET /volunteers/1.xml
  def show
    @volunteer = Volunteer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @volunteer }
    end
  end

  # GET /volunteers/new
  # GET /volunteers/new.xml
  def new
    @volunteer = Volunteer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @volunteer }
    end
  end

  # GET /volunteers/1/edit
  def edit
    @volunteer = Volunteer.find(params[:id])
  end

  # POST /volunteers
  # POST /volunteers.xml
  def create
    handle_image_upload(params)
    
    @volunteer = Volunteer.new(params[:volunteer])

    respond_to do |format|
      if @volunteer.save
        format.html { redirect_to(@volunteer, :notice => 'Volunteer was successfully created.') }
        format.xml  { render :xml => @volunteer, :status => :created, :location => @volunteer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @volunteer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /volunteers/1
  # PUT /volunteers/1.xml
  def update
    handle_image_upload(params)
    
    @volunteer = Volunteer.find(params[:id])

    respond_to do |format|
      if @volunteer.update_attributes(params[:volunteer])
        format.html { redirect_to(@volunteer, :notice => 'Volunteer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @volunteer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1
  # DELETE /volunteers/1.xml
  def destroy
    @volunteer = Volunteer.find(params[:id])
    @volunteer.destroy

    respond_to do |format|
      format.html { redirect_to(volunteers_url) }
      format.xml  { head :ok }
    end
  end
  
  private

  def handle_image_upload(params)
    if params[:image]
      uploaded_io = params[:image]
      File.open(Rails.root.join('public', 'images','volunteers',
          uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
      end
      params[:volunteer]['image'] = uploaded_io.original_filename
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/non_profits_helper.rb
module NonProfitsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facekick</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>

  <body id="volunteer">
      <div id="page-wrap">
           <header>
            <div id="header-wrap">
              <div id="logo-wrap">
                <a href="#">
                <h1 id="logo">Fundit</h1>
                <h2 id="tagline">A Place for Non-Profits</h2>
                </a>
              </div><!-- end of logo-wrap -->
              
              <ul id="funds">
                <li id="org"><h3>I'm a Non-Profit Organization</h3> <%= link_to 'Get Funds', new_non_profit_path %></li>
                <li id="vol"><h3>I'm a Volunteer or Donor</h3> <%= link_to 'Give Funds', new_volunteer_path %></li>
                <li id="banner"><span><h4>New Non-Profit</h4></span></li>
              </ul>
              
            <!--  <ul id="login">
                <li id="current-state">You are not logged in!</li>
                <li><a href="#">Register</a>|</li>
                <li><a href="volunteer.html">Login</a></li>
              </ul> -->
            </div>
           </header>



  

              <%= yield %>
            
              
  
           
        <footer>
          <div id="footer-wrap">
            <ul id="footer-cat-wrap">
              <li class="title">Categories
                <ul>
                  <li><a href="#">Art &amp; Media</a></li>
                  <li><a href="#">Communication</a></li>
                  <li><a href="#">Environmental</a></li>
                  <li><a href="#">Human Rights</a></li>
                  <li><a href="#">Animal Rights</a></li>
                </ul>
              </li>
              <li class="title">Contact
                <ul>
                  <li><address>P.O. Box 1869<br />Portland, OR</address></li>
                  <li>Phone 503.558.0550</li>
                  <li>Fax 503.558.0992</li>
                  <li><%= image_tag "mainpage/map.png" %></li>
                </ul>
              </li>
              <li class="title">Like us on Facebook
                <ul id="facebook">
                  <li class="clear"><a href="#"><%= image_tag "mainpage/facebook_like.png" %></a> 100 People like this</li>
                  <li class="clear">Grow Rice in South America<span class="like">5 People like this</span></li>
                  <li class="clear">1000 Tree Planting in New Mexico<span class="like">16 People like this</span></li>
                </ul>
              </li>
              <li class="title">Follow us on Twitter
                <ul id="twitter">
                  <li class="clear">Check out our organization of the day:<span class="org-day">http://waterdata.gov</span><span class="org-meta">6 hours ago | <a href="#">reply</a></span></li>
                  <li class="clear">Check out our organization of the day:<span class="org-day">http://waterdata.gov</span><span class="org-meta">8 days ago | <a href="#">reply</a></span></li>
                </ul>
              </li>
            </ul>
            <div id="footer-logo"><%= image_tag "mainpage/footer_logo.png" %></div>
          </div><!-- end of footer-wrap -->
        </footer> 
      </div><!-- end of page-wrap -->
        <!-- custom js -->
        <script type="text/javascript" src="js/custom.js"></script>
</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facekick</title>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
  
  <script>var $j = jQuery.noConflict();</script>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>


  <body>
      <div id="page-wrap">
           <header>
            <div id="header-wrap">
              <div id="logo-wrap">
                <a href="#">
                <h1 id="logo">Fundit</h1>
                <h2 id="tagline">A Place for Non-Profits</h2>
                </a>
              </div><!-- end of logo-wrap -->
              
              <ul id="funds">
                <li id="org"><h3>I'm a Non-Profit Organization</h3> <%= link_to 'Get Funds', new_non_profit_path %></li>
                <li id="vol"><h3>I'm a Volunteer or Donor</h3> <%= link_to 'Give Funds', new_volunteer_path %></li>
                <li id="banner"><span><h4>New Non-Profit</h4></span></li>
              </ul>
              
            <!--  <ul id="login">
                <li id="current-state">You are not logged in!</li>
                <li><a href="#">Register</a>|</li>
                <li><a href="volunteer.html">Login</a></li>
              </ul> -->
            </div>
           </header>

<%= yield %>

  
<div id="content-wrap">
              
            <div id="slideshow-wrap">
              <div id="slideshow-inner">
                
              <div id="slideshow">
                <%= image_tag "img1.jpg" %>
                <%= image_tag "img2.jpg" %>
                <%= image_tag "img3.jpg" %>
              </div><!-- end of slideshow -->
              
              <!-- captions for slideshow -->
              <span class="orbit-caption" id="htmlCaption"><strong>I'm A Badass Caption:</strong> I can haz <a href="#">links</a>, <em>style</em> or anything that is valid markup :)</span>
              
              </div><!-- end of slideshow-inner -->
            </div><!-- end of slideshow-wrap -->
              
  
            <div id="cat-wrap">
              <ul id="categories">
                <li id="first-cat"><a href="#">Art &amp; Media</a></li>
                <li><a href="#">Communication</a></li>
                <li><a href="#">Environmental</a></li>
                <li><a href="#">Human Rights</a></li>
                <li><a href="#">Animal Rights</a></li>
              </ul>
            </div><!-- end of cat-wrap -->
            
            <div id="ticker-wrap">
              <div id="ticker">
                <h3>Fundt helped raise &#36;<span id="ticker-money">5,053.45</span> and  <span id="ticker-hours">5645</span> hours so far.</h3>
              </div><!-- end of ticker -->
            </div><!-- end of ticker-wrap -->
              
              
            <div id="featured-wrap">
              <ul>
                
                <li><h4>Featured Organization</h4><span class="featured-img"><%= image_tag "featured1.jpg" %></span><span class="caption">Tree Planting</span><br /><a href="#">button</a></li>
                <li><h4>Featured Organization</h4><span class="featured-img"><%= image_tag "featured2.jpg" %></span><span class="caption">Grow Rice</span><br /><a href="#">button</a></li>
                
                 <% @volunteers.each do |volunteer| %>
                  <li><h4>Featured Volunteer</h4><span class="featured-img"><%= image_tag "volunteers/" + volunteer.get_image, :width=>'190px', :height=>'140px' %></span><span class="caption"><%= volunteer.name %></span><br /><a href="/volunteers/<%= volunteer.id %>"></a></li>
                <% end %>
                
              </ul>
            </div><!-- end of featured-wrap -->

            </div><!-- end of content-wrap -->


        <footer>
          <div id="footer-wrap">
            <ul id="footer-cat-wrap">
              <li class="title">Categories
                <ul>
                  <li><a href="#">Art &amp; Media</a></li>
                  <li><a href="#">Communication</a></li>
                  <li><a href="#">Environmental</a></li>
                  <li><a href="#">Human Rights</a></li>
                  <li><a href="#">Animal Rights</a></li>
                </ul>
              </li>
              <li class="title">Contact
                <ul>
                  <li><address>P.O. Box 1869<br />Portland, OR</address></li>
                  <li>Phone 503.558.0550</li>
                  <li>Fax 503.558.0992</li>
                  <li><%= image_tag "mainpage/map.png" %></li>
                </ul>
              </li>
              <li class="title">Like us on Facebook
                <ul id="facebook">
                  <li class="clear"><a href="#"><%= image_tag "mainpage/facebook_like.png" %></a> 100 People like this</li>
                  <li class="clear">Grow Rice in South America<span class="like">5 People like this</span></li>
                  <li class="clear">1000 Tree Planting in New Mexico<span class="like">16 People like this</span></li>
                </ul>
              </li>
              <li class="title">Follow us on Twitter
                <ul id="twitter">
                  <li class="clear">Check out our organization of the day:<span class="org-day">http://waterdata.gov</span><span class="org-meta">6 hours ago | <a href="#">reply</a></span></li>
                  <li class="clear">Check out our organization of the day:<span class="org-day">http://waterdata.gov</span><span class="org-meta">8 days ago | <a href="#">reply</a></span></li>
                </ul>
              </li>
            </ul>
            <div id="footer-logo"><%= image_tag "mainpage/footer_logo.png" %></div>
          </div><!-- end of footer-wrap -->
        </footer> 
      </div><!-- end of page-wrap -->
        <!-- custom js -->
        <script type="text/javascript" src="js/custom.js"></script>
</body>
</html>

app/views/non_profits/_form.html.erb
<%= form_for @non_profit, :html => {:multipart => true}  do |f| %>
  <% if @non_profit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@non_profit.errors.count, "error") %> prohibited this non_profit from being saved:</h2>

      <ul>
      <% @non_profit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :mission %><br />
    <%= f.text_field :mission %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= label :image, 'Image' %><br />
    <%= file_field_tag 'image' %>
  </div>
  <div class="field">
    <%= f.label :pledge %><br />
    <%= f.text_field :pledge %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.text_field :hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/non_profits/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @non_profit %> |
<%= link_to 'Back', non_profits_path %>

app/views/non_profits/index.html.erb
<h1>Listing non_profits</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Mission</th>
    <th>Bio</th>
    <th>Image</th>
    <th>Pledge</th>
    <th>Hours</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @non_profits.each do |non_profit| %>
  <tr>
    <td><%= non_profit.name %></td>
    <td><%= non_profit.mission %></td>
    <td><%= non_profit.bio %></td>
    <td><%= non_profit.image %></td>
    <td><%= non_profit.pledge %></td>
    <td><%= non_profit.hours %></td>
    <td><%= link_to 'Show', non_profit %></td>
    <td><%= link_to 'Edit', edit_non_profit_path(non_profit) %></td>
    <td><%= link_to 'Destroy', non_profit, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Non profit', new_non_profit_path %>

app/views/non_profits/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', non_profits_path %>

app/views/non_profits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @non_profit.name %>
</p>

<p>
  <b>Mission:</b>
  <%= @non_profit.mission %>
</p>

<p>
  <b>Bio:</b>
  <%= @non_profit.bio %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag "non_profits/" + @non_profit.get_image %>
</p>

<p>
  <b>Pledge:</b>
  <%= @non_profit.pledge %>
</p>

<p>
  <b>Hours:</b>
  <%= @non_profit.hours %>
</p>


<%= link_to 'Edit', edit_non_profit_path(@non_profit) %> |
<%= link_to 'Back', non_profits_path %>

app/views/volunteers/_form.html.erb
<%= form_for @volunteer, :html => {:multipart => true} do |f| %>
  <% if @volunteer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@volunteer.errors.count, "error") %> prohibited this volunteer from being saved:</h2>

      <ul>
      <% @volunteer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= label :image, 'Image' %><br />
    <%= file_field_tag 'image' %>
  </div>
  <div class="field">
    <%= f.label :pledge %><br />
    <%= f.text_field :pledge %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.text_field :hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/volunteers/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @volunteer %> |
<%= link_to 'Back', volunteers_path %>

app/views/volunteers/index.html.erb
<h1>Listing volunteers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Bio</th>
    <th>Image</th>
    <th>Pledge</th>
    <th>Hours</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @volunteers.each do |volunteer| %>
  <tr>
    <td><%= volunteer.name %></td>
    <td><%= volunteer.bio %></td>
    <td><%= volunteer.image %></td>
    <td><%= volunteer.pledge %></td>
    <td><%= volunteer.hours %></td>
    <td><%= link_to 'Show', volunteer %></td>
    <td><%= link_to 'Edit', edit_volunteer_path(volunteer) %></td>
    <td><%= link_to 'Destroy', volunteer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Volunteer', new_volunteer_path %>

app/views/volunteers/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', volunteers_path %>

app/views/volunteers/show.html.erb
<div id="content-wrap">
              <div id="content">

                <div id="bio">
                  <h3><%= @volunteer.name %><a href="#"><%= image_tag "subpages/twitter.png" %></a> <a href="#"><%= image_tag "subpages/linkedin.png" %></a> <a href="#"><%= image_tag "subpages/facebook.png" %></a></h3>
                  <h4>Funder &amp; Volunteer</h4>

                  <div id="bio-left">
                    <div><%= image_tag "volunteers/" + @volunteer.get_image, :width=>'220px', :height=>'220px' %></div>

                    <div id="medals">
                      <p><%= @volunteer.name %> has 2 gold medals!</p>
                      <ul>
                        <li><%= image_tag "subpages/gold_medal.png" %></li>
                        <li><%= image_tag "subpages/gold_medal.png" %></li>
                      </ul>
                    </div><!-- end of medals -->

                    <div id="rank">
                      <p>Until next rank</p>
                      <ul>
                        <li><%= image_tag "subpages/heart_full.png" %></li>
                        <li><%= image_tag "subpages/heart_half.png" %></li>
                        <li><%= image_tag "subpages/heart_empty.png" %></li>
                        <li><%= image_tag "subpages/heart_empty.png" %></li>
                        <li><%= image_tag "subpages/heart_empty.png" %></li>
                      </ul>
                    </div><!-- end of rank -->

                    <div id="count">
                      <ul>
                        <li><%= image_tag "subpages/dollar_sign.png" %> 8,045 Donated</li>
                        <li><%= image_tag "subpages/clock_sign.png" %> 5,432 Volunteered</li>
                      </ul>
                    </div><!-- end of count -->

                    <div id="contact">
                      <ul>
                        <li><a href="#" id="follow-button">Follow Button</a></li>
                        <li><a href="#" id="send-button">Send Message Button</a></li>
                      </ul>
                    </div><!-- end of contact -->

                  </div><!-- end of bio-left -->

                  <div id="bio-right">
                  <h5>Personal Statement</h5>
                  <p><%= @volunteer.bio %></p>
                  <div id="featured-wrap">
                    <ul>
                      <li><h4>Favorite Organization</h4><span class="featured-img"><%= image_tag "featured1.jpg" %></span><span class="caption">Tree Planting</span><br /><a href="#">Learn More</a></li>
                      <li><h4>Most Donated To</h4><span class="featured-img"><%= image_tag "featured1.jpg" %></span><span class="caption">Grow Rice</span><br /><a href="#">Learn More</a></li>
                    </ul>
                  </div><!-- end of featured-wrap -->

                  </div><!-- end of bio-right -->

                </div><!-- end of bio -->

                <aside>
                  <h6><%= @volunteer.name %>'s Calender</h6>
                  <div id="calender"><%= image_tag "subpages/calendar.png" %></div>

                  <div id="funded">
                    <h7>Funded</h7>
                    <div><%= image_tag "subpages/sidebar_thumbs.png" %></div>
                    <p><a href="#">View More</a></p>
                  </div><!-- end of funded -->

                  <div id="volunteered-for">
                    <h7>Volunteered For</h7>
                    <div><%= image_tag "subpages/sidebar_thumbs.png" %></div>
                    <p><a href="#">View More</a></p>
                  </div><!-- end of volunteered-for -->

                </aside>

              </div><!-- end of content -->
            </div><!-- end of content-wrap -->